/*
 * arch/arm/mach-tegra/board-yellowstone-pinmux-t12x.h
 *
 *
 * This program is free software; you can redistribute it and/or modify it
 * under the terms and conditions of the GNU General Public License,
 * version 2, as published by the Free Software Foundation.
 *
 * This program is distributed in the hope it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
 * more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */


static struct tegra_pingroup_config yellowstone_pinmux_common[] = {

	/* EXTPERIPH1 pinmux */
	DEFAULT_PINMUX(DAP_MCLK1,     EXTPERIPH1,  NORMAL,    NORMAL,   OUTPUT),

	/* I2S0 pinmux */
	DEFAULT_PINMUX(DAP1_DIN,      I2S0,        NORMAL,    NORMAL,   INPUT),
	DEFAULT_PINMUX(DAP1_DOUT,     I2S0,        NORMAL,    NORMAL,   INPUT),
	DEFAULT_PINMUX(DAP1_FS,       I2S0,        NORMAL,    NORMAL,   INPUT),
	DEFAULT_PINMUX(DAP1_SCLK,     I2S0,        NORMAL,    NORMAL,   INPUT),

	/* I2S1 pinmux */
	DEFAULT_PINMUX(DAP2_DIN,      I2S1,        NORMAL,    NORMAL,   INPUT),
	DEFAULT_PINMUX(DAP2_DOUT,     I2S1,        NORMAL,    NORMAL,   INPUT),
	DEFAULT_PINMUX(DAP2_FS,       I2S1,        NORMAL,    NORMAL,   INPUT),
	DEFAULT_PINMUX(DAP2_SCLK,     I2S1,        NORMAL,    NORMAL,   INPUT),

	/* CLDVFS pinmux */
	DEFAULT_PINMUX(DVFS_PWM,      CLDVFS,      NORMAL,    NORMAL,   OUTPUT),
	DEFAULT_PINMUX(DVFS_CLK,      CLDVFS,      NORMAL,    NORMAL,   OUTPUT),

	/* SPI1 pinmux */
	DEFAULT_PINMUX(ULPI_CLK,      SPI1,        NORMAL,    NORMAL,   OUTPUT),
	DEFAULT_PINMUX(ULPI_DIR,      SPI1,        NORMAL,    NORMAL,   INPUT),
	DEFAULT_PINMUX(ULPI_NXT,      SPI1,        NORMAL,    NORMAL,   OUTPUT),
	DEFAULT_PINMUX(ULPI_STP,      SPI1,        NORMAL,    NORMAL,   OUTPUT),

	/* SPI3 pinmux */
	DEFAULT_PINMUX(ULPI_DATA0,    SPI3,        NORMAL,    NORMAL,   OUTPUT),
	DEFAULT_PINMUX(ULPI_DATA1,    SPI3,        NORMAL,    NORMAL,   INPUT),
	DEFAULT_PINMUX(ULPI_DATA2,    SPI3,        NORMAL,    NORMAL,   OUTPUT),
	DEFAULT_PINMUX(ULPI_DATA3,    SPI3,        NORMAL,    NORMAL,   OUTPUT),

	/* I2C3 pinmux */
	I2C_PINMUX(CAM_I2C_SCL, I2C3, NORMAL, NORMAL, INPUT, DISABLE, ENABLE),
	I2C_PINMUX(CAM_I2C_SDA, I2C3, NORMAL, NORMAL, INPUT, DISABLE, ENABLE),

	/* I2C2 pinmux */
	I2C_PINMUX(GEN2_I2C_SCL, I2C2, NORMAL, NORMAL, INPUT, DISABLE, ENABLE),
	I2C_PINMUX(GEN2_I2C_SDA, I2C2, NORMAL, NORMAL, INPUT, DISABLE, ENABLE),

	/* UARTD pinmux */
	DEFAULT_PINMUX(GPIO_PJ7,      UARTD,       PULL_UP,    NORMAL,   OUTPUT),
	DEFAULT_PINMUX(GPIO_PB0,      UARTD,       PULL_UP,    NORMAL,   INPUT),

	/* SPI4 pinmux */
	DEFAULT_PINMUX(GPIO_PG5,      SPI4,        NORMAL,    NORMAL,   OUTPUT),
	DEFAULT_PINMUX(GPIO_PG6,      SPI4,        NORMAL,    NORMAL,   OUTPUT),
	DEFAULT_PINMUX(GPIO_PG7,      SPI4,        NORMAL,    NORMAL,   INPUT),
	DEFAULT_PINMUX(GPIO_PI3,      SPI4,        NORMAL,    NORMAL,   OUTPUT),

	/* PWM1 pinmux */
	DEFAULT_PINMUX(GPIO_PH1,      PWM1,        NORMAL,    NORMAL,   OUTPUT),

	/* SOC pinmux */
	DEFAULT_PINMUX(GPIO_PK0,     SOC,         PULL_UP,   NORMAL,   INPUT),
	DEFAULT_PINMUX(GPIO_PJ2,     SOC,         PULL_UP,   NORMAL,   INPUT),
	DEFAULT_PINMUX(KB_ROW15,     SOC,         PULL_UP,   NORMAL,   INPUT),
	DEFAULT_PINMUX(CLK_32K_OUT,   SOC,         PULL_UP,   NORMAL,   INPUT),

	/* USB pinmux */
	USB_PINMUX(USB_VBUS_EN2, USB, PULL_UP, NORMAL, OUTPUT, DISABLE, DISABLE),
	USB_PINMUX(USB_VBUS_EN0, USB, PULL_UP, NORMAL, INPUT, DEFAULT, DISABLE),

	/* SDMMC1 pinmux */
	DEFAULT_PINMUX(SDMMC1_CLK,    SDMMC1,      NORMAL,    NORMAL,   INPUT),
	DEFAULT_PINMUX(SDMMC1_CMD,    SDMMC1,      PULL_UP,   NORMAL,   INPUT),
	DEFAULT_PINMUX(SDMMC1_DAT0,   SDMMC1,      PULL_UP,   NORMAL,   INPUT),
	DEFAULT_PINMUX(SDMMC1_DAT1,   SDMMC1,      PULL_UP,   NORMAL,   INPUT),
	DEFAULT_PINMUX(SDMMC1_DAT2,   SDMMC1,      PULL_UP,   NORMAL,   INPUT),
	DEFAULT_PINMUX(SDMMC1_DAT3,   SDMMC1,      PULL_UP,   NORMAL,   INPUT),

	/* SDMMC3 pinmux */
	DEFAULT_PINMUX(SDMMC3_CLK,    SDMMC3,      NORMAL,    NORMAL,   OUTPUT),
	DEFAULT_PINMUX(SDMMC3_CMD,    SDMMC3,      PULL_UP,   NORMAL,   INPUT),
	DEFAULT_PINMUX(SDMMC3_DAT0,   SDMMC3,      PULL_UP,   NORMAL,   INPUT),
	DEFAULT_PINMUX(SDMMC3_DAT1,   SDMMC3,      PULL_UP,   NORMAL,   INPUT),
	DEFAULT_PINMUX(SDMMC3_DAT2,   SDMMC3,      PULL_UP,   NORMAL,   INPUT),
	DEFAULT_PINMUX(SDMMC3_DAT3,   SDMMC3,      PULL_UP,   NORMAL,   INPUT),
	DEFAULT_PINMUX(SDMMC3_CLK_LB_OUT, SDMMC3,  PULL_UP,   NORMAL,   INPUT),
	DEFAULT_PINMUX(SDMMC3_CLK_LB_IN, SDMMC3,   PULL_UP,   NORMAL,   INPUT),
	DEFAULT_PINMUX(SDMMC3_CD_N,   SDMMC3,      PULL_UP,   NORMAL,   INPUT),

	/* SDMMC4 pinmux */
	DEFAULT_PINMUX(SDMMC4_CLK,    SDMMC4,      NORMAL,    NORMAL,   INPUT),
	DEFAULT_PINMUX(SDMMC4_CMD,    SDMMC4,      PULL_UP,   NORMAL,   INPUT),
	DEFAULT_PINMUX(SDMMC4_DAT0,   SDMMC4,      PULL_UP,   NORMAL,   INPUT),
	DEFAULT_PINMUX(SDMMC4_DAT1,   SDMMC4,      PULL_UP,   NORMAL,   INPUT),
	DEFAULT_PINMUX(SDMMC4_DAT2,   SDMMC4,      PULL_UP,   NORMAL,   INPUT),
	DEFAULT_PINMUX(SDMMC4_DAT3,   SDMMC4,      PULL_UP,   NORMAL,   INPUT),
	DEFAULT_PINMUX(SDMMC4_DAT4,   SDMMC4,      PULL_UP,   NORMAL,   INPUT),
	DEFAULT_PINMUX(SDMMC4_DAT5,   SDMMC4,      PULL_UP,   NORMAL,   INPUT),
	DEFAULT_PINMUX(SDMMC4_DAT6,   SDMMC4,      PULL_UP,   NORMAL,   INPUT),
	DEFAULT_PINMUX(SDMMC4_DAT7,   SDMMC4,      PULL_UP,   NORMAL,   INPUT),

	/* I2CPWR pinmux */
	I2C_PINMUX(PWR_I2C_SCL, I2CPWR, NORMAL, NORMAL, INPUT, DEFAULT, ENABLE),
	I2C_PINMUX(PWR_I2C_SDA, I2CPWR, NORMAL, NORMAL, INPUT, DEFAULT, ENABLE),

	/* RTCK pinmux */
	DEFAULT_PINMUX(JTAG_RTCK,     RTCK,        PULL_UP,    NORMAL,   OUTPUT),

	/* CLK pinmux */
	DEFAULT_PINMUX(CLK_32K_IN,   CLK,         NORMAL,    NORMAL,   INPUT),

	/* PWRON pinmux */
	DEFAULT_PINMUX(CORE_PWR_REQ,  PWRON,       NORMAL,    NORMAL,   OUTPUT),

	/* CPU pinmux */
	DEFAULT_PINMUX(CPU_PWR_REQ,   CPU,         NORMAL,    NORMAL,   OUTPUT),

	/* PMI pinmux */
	DEFAULT_PINMUX(PWR_INT_N,     PMI,         PULL_UP,    NORMAL,   INPUT),

	/* RESET_OUT_N pinmux */
	DEFAULT_PINMUX(RESET_OUT_N,   RESET_OUT_N, NORMAL,    NORMAL,   OUTPUT),

	/* I2S3 pinmux */
	DEFAULT_PINMUX(DAP4_DIN,      I2S3,        NORMAL,    NORMAL,   INPUT),
	DEFAULT_PINMUX(DAP4_DOUT,     I2S3,        NORMAL,    NORMAL,   INPUT),
	DEFAULT_PINMUX(DAP4_FS,       I2S3,        NORMAL,    NORMAL,   INPUT),
	DEFAULT_PINMUX(DAP4_SCLK,     I2S3,        NORMAL,    NORMAL,   INPUT),

	/* I2C1 pinmux */
	I2C_PINMUX(GEN1_I2C_SCL, I2C1, NORMAL, NORMAL, INPUT, DISABLE, ENABLE),
	I2C_PINMUX(GEN1_I2C_SDA, I2C1, NORMAL, NORMAL, INPUT, DISABLE, ENABLE),

	/* UARTA pinmux */
	DEFAULT_PINMUX(GPIO_PU0,      UARTA,       NORMAL,    NORMAL,   OUTPUT),
	DEFAULT_PINMUX(GPIO_PU1,      UARTA,       PULL_UP,    NORMAL,   INPUT),

	/* UARTB pinmux */
	DEFAULT_PINMUX(UART2_CTS_N,   UARTB,       NORMAL,   NORMAL,   INPUT),
	DEFAULT_PINMUX(UART2_RTS_N,   UARTB,       NORMAL,   NORMAL,   OUTPUT),

	/* IRDA pinmux */
	DEFAULT_PINMUX(UART2_RXD,     IRDA,        NORMAL,    NORMAL,   INPUT),
	DEFAULT_PINMUX(UART2_TXD,     IRDA,        NORMAL,    NORMAL,   OUTPUT),

	/* UARTC pinmux */
	DEFAULT_PINMUX(UART3_CTS_N,   UARTC,       NORMAL,    NORMAL,   INPUT),
	DEFAULT_PINMUX(UART3_RTS_N,   UARTC,       NORMAL,    NORMAL,   OUTPUT),
	DEFAULT_PINMUX(UART3_RXD,     UARTC,       PULL_UP,   NORMAL,   INPUT),
	DEFAULT_PINMUX(UART3_TXD,     UARTC,       NORMAL,    NORMAL,   OUTPUT),

	/* CEC pinmux */
	CEC_PINMUX(HDMI_CEC, CEC, NORMAL, NORMAL, INPUT, DEFAULT, ENABLE),

	/* I2C4 pinmux */
	DDC_PINMUX(DDC_SCL, I2C4, NORMAL, NORMAL, INPUT, DEFAULT, NORMAL),
	DDC_PINMUX(DDC_SDA, I2C4, NORMAL, NORMAL, INPUT, DEFAULT, NORMAL),

	/* GPIO pinmux */
	DEFAULT_PINMUX(GPIO_X5_AUD, RSVD4, NORMAL, NORMAL, INPUT),
	DEFAULT_PINMUX(GPIO_X6_AUD, GMI, NORMAL, NORMAL, OUTPUT),
	DEFAULT_PINMUX(GPIO_X7_AUD, RSVD1, NORMAL, NORMAL, OUTPUT),
	DEFAULT_PINMUX(GPIO_X1_AUD, RSVD2, NORMAL, NORMAL, OUTPUT),
	DEFAULT_PINMUX(GPIO_X3_AUD, RSVD4, PULL_UP, NORMAL, INPUT),
	DEFAULT_PINMUX(GPIO_PV0,    RSVD1, PULL_UP, NORMAL, INPUT),
	DEFAULT_PINMUX(GPIO_PV1,    RSVD1, PULL_UP, NORMAL, INPUT),
	DEFAULT_PINMUX(ULPI_DATA4,    ULPI,  PULL_UP,    NORMAL,   INPUT),
	DEFAULT_PINMUX(ULPI_DATA5,    ULPI,  NORMAL,    NORMAL,   OUTPUT),
	DEFAULT_PINMUX(GPIO_PBB4,       VGP4,  PULL_DOWN,    NORMAL,     OUTPUT),
	DEFAULT_PINMUX(GPIO_PBB6, RSVD2, NORMAL, NORMAL, OUTPUT),
	DEFAULT_PINMUX(GPIO_PBB7, RSVD2, PULL_UP, NORMAL, OUTPUT),
	DEFAULT_PINMUX(GPIO_PCC1, RSVD2, PULL_UP, NORMAL, OUTPUT),
	DEFAULT_PINMUX(GPIO_PH0, GMI, PULL_UP, NORMAL, INPUT),
	DEFAULT_PINMUX(GPIO_PH2, GMI, NORMAL, NORMAL, OUTPUT),
	DEFAULT_PINMUX(GPIO_PH3, GMI, NORMAL, NORMAL, OUTPUT),
	DEFAULT_PINMUX(GPIO_PH4, GMI, PULL_UP, NORMAL, INPUT),
	DEFAULT_PINMUX(GPIO_PH5, GMI, NORMAL, NORMAL, OUTPUT),
	DEFAULT_PINMUX(GPIO_PH7, GMI, PULL_UP, NORMAL, INPUT),
	DEFAULT_PINMUX(GPIO_PI0, RSVD1, NORMAL, NORMAL, OUTPUT),
	DEFAULT_PINMUX(GPIO_PI2, RSVD4, PULL_UP, NORMAL, OUTPUT),
	DEFAULT_PINMUX(GPIO_PI4, GMI, NORMAL, NORMAL, INPUT),
	DEFAULT_PINMUX(GPIO_PI5, RSVD2, NORMAL, NORMAL, INPUT),
	DEFAULT_PINMUX(GPIO_PI6, RSVD1, NORMAL, NORMAL, INPUT),
	DEFAULT_PINMUX(GPIO_PI7, RSVD1, NORMAL, NORMAL, INPUT),
	DEFAULT_PINMUX(GPIO_PK1, RSVD4, NORMAL, NORMAL, OUTPUT),
	DEFAULT_PINMUX(GPIO_PK2, RSVD1, PULL_UP, NORMAL, INPUT),
	DEFAULT_PINMUX(GPIO_PK4, RSVD2, NORMAL, NORMAL, OUTPUT),
	DEFAULT_PINMUX(GPIO_PJ0,    RSVD1, PULL_UP, NORMAL, INPUT),
	DEFAULT_PINMUX(KB_COL0, RSVD2, PULL_UP, NORMAL, INPUT),
	DEFAULT_PINMUX(KB_COL1, RSVD2, NORMAL, NORMAL, OUTPUT),
	DEFAULT_PINMUX(KB_COL2, RSVD2, NORMAL, NORMAL, OUTPUT),
	DEFAULT_PINMUX(KB_COL3, KBC, NORMAL, NORMAL, OUTPUT),
	DEFAULT_PINMUX(KB_COL4, KBC, NORMAL, NORMAL, OUTPUT),
	DEFAULT_PINMUX(KB_COL6, RSVD2, PULL_UP, NORMAL, INPUT),
	DEFAULT_PINMUX(KB_COL7, RSVD2, PULL_UP, NORMAL, INPUT),
	DEFAULT_PINMUX(KB_ROW0, RSVD2, NORMAL, NORMAL, OUTPUT),
	DEFAULT_PINMUX(KB_ROW1, RSVD2, NORMAL, NORMAL, OUTPUT),
	DEFAULT_PINMUX(KB_ROW2, RSVD2, NORMAL, NORMAL, OUTPUT),
	DEFAULT_PINMUX(KB_ROW4, RSVD3, PULL_DOWN, NORMAL, INPUT),
	DEFAULT_PINMUX(KB_ROW5, RSVD3, NORMAL, NORMAL, OUTPUT),
	DEFAULT_PINMUX(KB_ROW6, KBC, PULL_DOWN, NORMAL, INPUT),
	DEFAULT_PINMUX(KB_ROW7, RSVD2, PULL_UP, NORMAL, INPUT),
	DEFAULT_PINMUX(KB_ROW8, RSVD2, NORMAL, NORMAL, INPUT),
	DEFAULT_PINMUX(KB_ROW9, RSVD2, NORMAL, NORMAL, INPUT),
	DEFAULT_PINMUX(KB_ROW10, RSVD2, NORMAL, NORMAL, INPUT),
	DEFAULT_PINMUX(KB_ROW11, RSVD2, NORMAL, NORMAL, OUTPUT),
	DEFAULT_PINMUX(KB_ROW12, RSVD2, NORMAL, NORMAL, OUTPUT),
	DEFAULT_PINMUX(KB_ROW13, RSVD2, PULL_DOWN, NORMAL, OUTPUT),
	DEFAULT_PINMUX(KB_ROW14, RSVD2, PULL_DOWN, NORMAL, OUTPUT),
	DEFAULT_PINMUX(CLK3_REQ, RSVD2, NORMAL, NORMAL, OUTPUT),
	DEFAULT_PINMUX(GPIO_PU5, GMI, PULL_DOWN, NORMAL, INPUT),
	DEFAULT_PINMUX(GPIO_PU6, RSVD3, PULL_DOWN, NORMAL, INPUT),
	DEFAULT_PINMUX(HDMI_INT, RSVD1, PULL_DOWN, NORMAL, INPUT),
	DEFAULT_PINMUX(SPDIF_OUT, RSVD2, NORMAL, NORMAL, OUTPUT),
	DEFAULT_PINMUX(SPDIF_IN, RSVD2, NORMAL, NORMAL, OUTPUT),
	DEFAULT_PINMUX(USB_VBUS_EN1, RSVD2, NORMAL, NORMAL, OUTPUT),
	DEFAULT_PINMUX(DP_HPD, RSVD2, PULL_UP, NORMAL, INPUT),
};

static struct tegra_pingroup_config unused_pins_lowpower[] = {
	UNUSED_PINMUX(DAP_MCLK1_REQ),
	UNUSED_PINMUX(GPIO_X4_AUD),
	UNUSED_PINMUX(GPIO_W2_AUD),
	UNUSED_PINMUX(GPIO_W3_AUD),
	UNUSED_PINMUX(DAP3_DIN),
	UNUSED_PINMUX(DAP3_DOUT),
	UNUSED_PINMUX(DAP3_FS),
	UNUSED_PINMUX(DAP3_SCLK),
	UNUSED_PINMUX(ULPI_DATA6),
	UNUSED_PINMUX(ULPI_DATA7),
	UNUSED_PINMUX(CAM_MCLK),
	UNUSED_PINMUX(GPIO_PBB0),
	UNUSED_PINMUX(GPIO_PBB3),
	UNUSED_PINMUX(GPIO_PBB5),
	UNUSED_PINMUX(GPIO_PCC2),
	UNUSED_PINMUX(GPIO_PB1),
	UNUSED_PINMUX(GPIO_PI1),
	UNUSED_PINMUX(GPIO_PH6),
	UNUSED_PINMUX(GPIO_PK7),
	UNUSED_PINMUX(GPIO_PG0),
	UNUSED_PINMUX(GPIO_PG1),
	UNUSED_PINMUX(GPIO_PG2),
	UNUSED_PINMUX(GPIO_PG3),
	UNUSED_PINMUX(GPIO_PG4),
	UNUSED_PINMUX(GPIO_PK3),
	UNUSED_PINMUX(GPIO_PC7),
	UNUSED_PINMUX(PEX_L0_CLKREQ_N),
	UNUSED_PINMUX(PEX_L0_RST_N),
	UNUSED_PINMUX(PEX_L1_CLKREQ_N),
	UNUSED_PINMUX(PEX_L1_RST_N),
	UNUSED_PINMUX(PEX_WAKE_N),
	UNUSED_PINMUX(GPIO_PFF2),
	UNUSED_PINMUX(CLK2_OUT),
	UNUSED_PINMUX(CLK2_REQ),
	UNUSED_PINMUX(SDMMC1_WP_N),
	UNUSED_PINMUX(KB_COL5),
	UNUSED_PINMUX(KB_ROW16),
	UNUSED_PINMUX(KB_ROW17),
	UNUSED_PINMUX(KB_ROW3),
	UNUSED_PINMUX(GPIO_PU2),
	UNUSED_PINMUX(GPIO_PU3),
	UNUSED_PINMUX(GPIO_PU4),
	UNUSED_PINMUX(OWR),
};

static struct gpio_init_pin_info init_gpio_mode_yellowstone_common[] = {
	GPIO_INIT_PIN_MODE(TEGRA_GPIO_PX5, true, 0),
	GPIO_INIT_PIN_MODE(TEGRA_GPIO_PX3, true, 0),
	GPIO_INIT_PIN_MODE(TEGRA_GPIO_PV0, true, 0),
	GPIO_INIT_PIN_MODE(TEGRA_GPIO_PV1, true, 0),
	GPIO_INIT_PIN_MODE(TEGRA_GPIO_PO5, true, 0),
	GPIO_INIT_PIN_MODE(TEGRA_GPIO_PH4, true, 0),
	GPIO_INIT_PIN_MODE(TEGRA_GPIO_PH6, true, 0),
	GPIO_INIT_PIN_MODE(TEGRA_GPIO_PH7, true, 0),
	GPIO_INIT_PIN_MODE(TEGRA_GPIO_PH0, true, 0),
	GPIO_INIT_PIN_MODE(TEGRA_GPIO_PJ0, true, 0),
	GPIO_INIT_PIN_MODE(TEGRA_GPIO_PK2, true, 0),
	GPIO_INIT_PIN_MODE(TEGRA_GPIO_PI6, true, 0),
	GPIO_INIT_PIN_MODE(TEGRA_GPIO_PI5, true, 0),
	GPIO_INIT_PIN_MODE(TEGRA_GPIO_PI1, true, 0),
	GPIO_INIT_PIN_MODE(TEGRA_GPIO_PI4, true, 0),
	GPIO_INIT_PIN_MODE(TEGRA_GPIO_PI7, true, 0),
	GPIO_INIT_PIN_MODE(TEGRA_GPIO_PQ0, true, 0),
	GPIO_INIT_PIN_MODE(TEGRA_GPIO_PQ6, true, 0),
	GPIO_INIT_PIN_MODE(TEGRA_GPIO_PQ7, true, 0),
	GPIO_INIT_PIN_MODE(TEGRA_GPIO_PS0, true, 0),
	GPIO_INIT_PIN_MODE(TEGRA_GPIO_PS1, true, 0),
	GPIO_INIT_PIN_MODE(TEGRA_GPIO_PS2, true, 0),
	GPIO_INIT_PIN_MODE(TEGRA_GPIO_PR6, true, 0),
	GPIO_INIT_PIN_MODE(TEGRA_GPIO_PR7, true, 0),
	GPIO_INIT_PIN_MODE(TEGRA_GPIO_PR4, true, 0),
	GPIO_INIT_PIN_MODE(TEGRA_GPIO_PU5, true, 0),
	GPIO_INIT_PIN_MODE(TEGRA_GPIO_PU6, true, 0),
	GPIO_INIT_PIN_MODE(TEGRA_GPIO_PN4, false, 0),
	GPIO_INIT_PIN_MODE(TEGRA_GPIO_PN7, true, 0),
	GPIO_INIT_PIN_MODE(TEGRA_GPIO_PFF0, true, 1),
	GPIO_INIT_PIN_MODE(TEGRA_GPIO_PFF1, false, 1),

	GPIO_INIT_PIN_MODE(TEGRA_GPIO_PX6, false, 0),
	GPIO_INIT_PIN_MODE(TEGRA_GPIO_PX7, false, 0),
	GPIO_INIT_PIN_MODE(TEGRA_GPIO_PO6, false, 0),
	GPIO_INIT_PIN_MODE(TEGRA_GPIO_PBB4, false, 0),
	GPIO_INIT_PIN_MODE(TEGRA_GPIO_PBB6, false, 0),
	GPIO_INIT_PIN_MODE(TEGRA_GPIO_PBB7, false, 0),
	GPIO_INIT_PIN_MODE(TEGRA_GPIO_PCC1, false, 0),
	GPIO_INIT_PIN_MODE(TEGRA_GPIO_PH2, false, 0),
	GPIO_INIT_PIN_MODE(TEGRA_GPIO_PH3, false, 0),
	GPIO_INIT_PIN_MODE(TEGRA_GPIO_PH5, false, 0),
	GPIO_INIT_PIN_MODE(TEGRA_GPIO_PK1, false, 0),
	GPIO_INIT_PIN_MODE(TEGRA_GPIO_PK4, false, 0),
	GPIO_INIT_PIN_MODE(TEGRA_GPIO_PI2, false, 0),
	GPIO_INIT_PIN_MODE(TEGRA_GPIO_PI0, false, 0),
	GPIO_INIT_PIN_MODE(TEGRA_GPIO_PQ1, false, 0),
	GPIO_INIT_PIN_MODE(TEGRA_GPIO_PQ3, false, 0),
	GPIO_INIT_PIN_MODE(TEGRA_GPIO_PR0, false, 1),
	GPIO_INIT_PIN_MODE(TEGRA_GPIO_PR1, false, 0),
	GPIO_INIT_PIN_MODE(TEGRA_GPIO_PS3, false, 0),
	GPIO_INIT_PIN_MODE(TEGRA_GPIO_PS4, false, 0),
	GPIO_INIT_PIN_MODE(TEGRA_GPIO_PS5, false, 0),
	GPIO_INIT_PIN_MODE(TEGRA_GPIO_PS6, false, 0),
	GPIO_INIT_PIN_MODE(TEGRA_GPIO_PR2, false, 0),
	GPIO_INIT_PIN_MODE(TEGRA_GPIO_PR5, false, 0),
	GPIO_INIT_PIN_MODE(TEGRA_GPIO_PEE1, false, 0),
	GPIO_INIT_PIN_MODE(TEGRA_GPIO_PK5, false, 0),
	GPIO_INIT_PIN_MODE(TEGRA_GPIO_PK6, false, 0),
	GPIO_INIT_PIN_MODE(TEGRA_GPIO_PN5, false, 0),
	GPIO_INIT_PIN_MODE(TEGRA_GPIO_PQ2, false, 1),
	GPIO_INIT_PIN_MODE(TEGRA_GPIO_PQ4, false, 1),
	GPIO_INIT_PIN_MODE(TEGRA_GPIO_PX1, false, 0),
};
